// react-test/src/components/header.jsx
import React from 'react';
// appIdをconfigから直接インポート
import QrImg from '../assets/images/qr.png';

const QrCodeImage = () => <img src={QrImg} alt="入場用QRコード" className="w-full h-full object-contain" />;

export const Header = ({ userId, isLoading, data }) => {
    // configから直接appIdを取得
    const appId = globalAppId; 

    // dataがnullの場合のフォールバックを初期データとして設定
    const defaultData = {
        currentCount: 0, localInCount: 0, exitInCount: 0, waitTime: '--',
        day1Date: '[--/--]', day1Visitors: 0, day2Date: '[--/--]', day2Visitors: 0,
        totalVisitors: 0,
    };
    const displayData = data || defaultData;

    return (
        // bg-cyan-view は tailwind.config.js で定義されたカスタムカラー
        <header id="info-header" className="bg-cyan-view text-white p-2 flex-shrink-0 z-10 shadow-lg">
            <div className="max-w-4xl mx-auto flex justify-between items-start space-x-4">
                
                {/* QRコードコンテナ */}
                <div id="qr-code-container" className="w-24 h-24 flex-shrink-0 bg-white p-1 rounded-lg shadow-inner flex items-center justify-center border-2 border-cyan-200">
                    {/* QrCodeImageコンポーネントを配置 */}
                    <QrCodeImage />
                </div>

                {/* 情報エリア */}
                <div className="flex-1 flex flex-col justify-between space-y-2 min-w-0 text-right">
                    
                    {/* 場内人数表示 */}
                    <div id="current-count-display" className="text-lg md:text-lg font-bold flex items-end justify-end flex-wrap gap-x-2">
                        場内人数:
                        <span id="current-count-value" className="ml-2 text-4xl text-yellow-300 tabular-nums">
                            {displayData.currentCount}
                        </span>
                        <span className="text-sm md:text-base opacity-80">
                            （内、優先入場:<span id="localin-count" className="tabular-nums">{displayData.localInCount}</span>
                            出口:<span id="exitin-count" className="tabular-nums">{displayData.exitInCount}</span>）
                        </span>
                    </div>

                    {/* 待ち時間表示 */}
                    <div id="wait-time-display" className="w-full text-base md:text-lg font-light opacity-95">
                        100人当たり待ち時間:
                        <span id="wait-time-value" className="font-bold tabular-nums ml-1">
                            {displayData.waitTime}
                        </span>分
                    </div>

                    {/* 過去来場者数表示 */}
                    <div className="w-full text-sm md:text-base font-light opacity-90 pt-1 border-t border-cyan-400/50">
                        <span id="event-day1-date">{displayData.day1Date}</span>
                        <span className="font-bold ml-1 tabular-nums" id="day1-visitors">：{displayData.day1Visitors}人</span>
                        
                        <span className="mx-2 hidden sm:inline"></span>
                        <br className="sm:hidden"/> 

                        <span id="event-day2-date">{displayData.day2Date}</span>
                        <span className="font-bold ml-1 tabular-nums" id="day2-visitors">：{displayData.day2Visitors}人</span>
                        
                        <span className="mx-2"></span>
                        
                        <span>[計]</span>
                        <span className="font-bold ml-1 tabular-nums" id="total-visitors">：{displayData.totalVisitors}人</span>
                    </div>
                </div>
            </div>
            
            {/* 認証情報表示 (デバッグ用/ユーザー識別用) */}
            <div className="max-w-4xl mx-auto pt-1 mt-1 border-t border-cyan-400/50 text-right">
                {isLoading ? (
                    <span className="text-xs text-gray-200">認証中...</span>
                ) : (
                    <div className="text-xs text-gray-200 truncate max-w-full">
                        User ID: {userId || 'N/A'} (App ID: {appId})
                    </div>
                )}
            </div>
        </header>
    );
};

// vue-test/src/components/Header.vue
<template>
  <header class="bg-cyan-view text-white p-1 flex-shrink-0 z-10 shadow">
    <div class="max-w-4xl mx-auto flex justify-between items-start space-x-4">
      <!-- QR -->
      <div class="w-24 h-24 flex-shrink-0 bg-white p-1 rounded-lg shadow-inner flex items-center justify-center border-2 border-cyan-200">
        <img v-if="qrAvailable" src="/qr.png" alt="QRコード" class="object-contain rounded w-full h-full" />
        <div v-else class="text-xs text-gray-400 text-center">QR画像未設定</div>
      </div>

      <!-- 情報エリア -->
      <div class="flex-1 flex flex-col justify-between space-y-2 min-w-0 text-right">
        <div class="text-lg font-bold flex items-end justify-end flex-wrap gap-x-2">
          場内人数:
          <span class="ml-2 text-4xl text-yellow-400 tabular-nums">{{ currentCount }}</span>
          <span class="text-sm opacity-80">
            （内、優先入場:{{ localIn }} 出口:{{ exitIn }}）
          </span>
        </div>

        <div class="text-base font-light opacity-95">
          100人当たり待ち時間:
          <span class="font-bold tabular-nums">{{ waitTime }}分</span>
        </div>

        <div class="text-base font-light opacity-90 pt-1 border-t border-cyan-400/50">
          <span>[{{ date1 }}]</span><span class="font-bold ml-1 tabular-nums">：{{ day1Total }}人</span>
          <span class="mx-2"></span>
          <span>[{{ date2 }}]</span><span class="font-bold ml-1 tabular-nums">：{{ day2Total }}人</span>
          <span class="mx-2"></span>
          <span>[計]</span><span class="font-bold ml-1 tabular-nums">：{{ totalVisitors }}人</span>
        </div>
      </div>
    </div>
  </header>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { useHeaderData } from "@/composables/useHeaderData.js";

const qrAvailable = true;

// データ取得
const {
  currentCount,
  localIn,
  exitIn,
  waitTime,
  date1,
  date2,
  day1Total,
  day2Total,
  totalVisitors,
  initHeaderData
} = useHeaderData();

onMounted(() => {
  initHeaderData("setapanmarketcounter");
});
</script>
